# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: telegram-owl

before:
  hooks:
    - go mod tidy

builds:
  - binary: telegram-owl
    main: ./cmd/telegram-owl
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: freebsd
        goarch: arm
    goarm:
      - 7
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/beeyev/telegram-owl/internal/version.version={{.Version}}


archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}64bit
      {{- else if eq .Arch "386" }}32bit
      {{- else if eq .Arch "arm" }}ARM
      {{- else if eq .Arch "arm64" }}ARM64
      {{- else }}{{ .Arch }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "telegram-owl_v{{.Version}}_checksums.txt"

changelog:
  disable: true

report_sizes: true

release:
  mode: append
  footer: |
    # Install

    ## macOS and Linux
    ### Install with [`Homebrew`](https://brew.sh)
    ```console
    brew tap beeyev/pkg https://github.com/beeyev/pkg
    brew install telegram-owl
    ```
    ## Windows
    ### Install with [`Scoop`](https://scoop.sh)
    ```console
    scoop bucket add beeyev https://github.com/beeyev/pkg
    scoop install telegram-owl
    ```
    ### Install with `winget`
    ```console
    winget install telegram-owl
    ```

    ## Anywhere else
    Alternatively, you can install the latest binary from this page.

    ### Manual downloads
    Download for Windows [64bit](https://github.com/beeyev/telegram-owl/releases/download/v{{.Version}}/telegram-owl_v{{.Version}}_Windows_64bit.zip) / [32bit](https://github.com/beeyev/telegram-owl/releases/download/v{{.Version}}/telegram-owl_v{{.Version}}_Windows_32bit.zip) / [Arm64](https://github.com/beeyev/telegram-owl/releases/download/v{{.Version}}/telegram-owl_v{{.Version}}_Windows_ARM64.zip) / [Arm](https://github.com/beeyev/telegram-owl/releases/download/v{{.Version}}/telegram-owl_v{{.Version}}_Windows_ARM.zip)
    Download for Linux [64bit](https://github.com/beeyev/telegram-owl/releases/download/v{{.Version}}/telegram-owl_v{{.Version}}_Linux_64bit.tar.gz) / [32bit](https://github.com/beeyev/telegram-owl/releases/download/v{{.Version}}/telegram-owl_v{{.Version}}_Linux_32bit.tar.gz) / [Arm64](https://github.com/beeyev/telegram-owl/releases/download/v{{.Version}}/telegram-owl_v{{.Version}}_Linux_ARM64.tar.gz) / [Arm](https://github.com/beeyev/telegram-owl/releases/download/v{{.Version}}/telegram-owl_v{{.Version}}_Linux_ARM.tar.gz)
    Download for macOS [64bit](https://github.com/beeyev/telegram-owl/releases/download/v{{.Version}}/telegram-owl_v{{.Version}}_macOS_64bit.tar.gz) / [32bit](https://github.com/beeyev/telegram-owl/releases/download/v{{.Version}}/telegram-owl_v{{.Version}}_macOS_ARM64.tar.gz)

    For more options, check the `Assets` sections below ↓

chocolateys:
  -
    name: telegram-owl
    package_source_url: https://github.com/beeyev/telegram-owl
    owners: Alexander Tebiev
    title: Telegram Owl
    authors: Alexander Tebiev
    project_url: https://github.com/beeyev/telegram-owl
    # icon_url: "https://rawcdn.githack.com/foo/bar/efbdc760-395b-43f1-bf69-ba25c374d473/icon.png"
    copyright: Alexander Tebiev
    license_url: https://github.com/beeyev/telegram-owl/blob/master/LICENSE
    require_license_acceptance: false
    project_source_url: https://github.com/beeyev/telegram-owl
    docs_url: https://github.com/beeyev/telegram-owl/blob/master/README.md
    bug_tracker_url: https://github.com/beeyev/telegram-owl/issues
    tags: "telegram"
    summary: CLI utility to send messages and files to Telegram chats and channels
    description: |
      {{ .ProjectName }} installer package.
      CLI utility to send messages and files to Telegram chats and channels
    release_notes: "https://github.com/beeyev/telegram-owl/releases/tag/v{{ .Version }}"
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    source_repo: "https://push.chocolatey.org/"
