# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: telegram-owl

before:
  hooks:
    - go mod tidy

builds:
  - binary: telegram-owl
    main: ./cmd/telegram-owl
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: freebsd
        goarch: arm
    goarm:
      - 7
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/beeyev/telegram-owl/internal/version.version={{.Version}}


archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}64bit
      {{- else if eq .Arch "386" }}32bit
      {{- else if eq .Arch "arm" }}ARM
      {{- else if eq .Arch "arm64" }}ARM64
      {{- else }}{{ .Arch }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "telegram-owl_v{{.Version}}_checksums.txt"

changelog:
  use: github
  sort: asc

upx:
  - enabled: true
    goos:
      - linux
      - windows
    compress: best
    lzma: true
    brute: false

report_sizes: true

release:
  footer: |
    ## Install

    #### macOS and Linux
    ##### Install with [Homebrew](https://brew.sh) (recommended)
    ```console
    brew install beeyev/tap/telegram-owl
    ```
    #### Windows
    ##### Install with [Scoop](https://scoop.sh)
    ```console
    scoop bucket add beeyev https://github.com/beeyev/scoop-bucket
    scoop install telegram-owl
    ```
    ##### Install with [Chocolatey](https://chocolatey.org)
    ```console
    choco install telegram-owl
    ```

    #### Anywhere else
    Alternatively, you can install the latest binary from this page.

    ## Update
    Update to the latest version depends on how you choose to install `telegram-owl` on your machine.
    #### Update with [Homebrew](https://brew.sh)
    ```console
    brew upgrade telegram-owl
    ```
    #### Update with [Scoop](https://scoop.sh)
    ```console
    scoop update telegram-owl
    ```
    #### Update with [Chocolatey](https://chocolatey.org)
    ```console
    choco upgrade telegram-owl
    ```

    Alternatively, you can grab the latest binary (or the apt/rpm/deb package) from this page.

scoops:
  -
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/beeyev/telegram-owl"
    description: "CLI utility to send messages and files to Telegram chats and channels"
    license: MIT
    # A two-dimensional array of string, specifies the shortcut values to make available in the startmenu.
    # The array has to contain an executable/label pair. The third and fourth element are optional.
    #shortcuts: [["drumroll.exe", "drumroll"]]
    repository:
      owner: beeyev
      name: pkg
      #name: scoop-bucket

brews:
  -
    goarm: 7
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    homepage: "https://github.com/beeyev/telegram-owl"
    description: "CLI utility to send messages and files to Telegram chats and channels"
    license: "MIT"
    test: |
      assert_match version.to_s, shell_output("#{bin}/telegram-owl --version")
    repository:
      owner: beeyev
      name: pkg
      #name: homebrew-tap

winget:
  -
    publisher: Alexander Tebiev
    short_description: "CLI utility to send messages and files to Telegram chats and channels"
    license: "MIT"
    publisher_url: "https://github.com/beeyev/telegram-owl"
    publisher_support_url: "https://github.com/beeyev/telegram-owl/issues"
    package_identifier: beeyev.telegram-owl
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "{{ .PackageIdentifier }}: {{ .Tag }}"
    # Path for the file inside the repository.
    #
    # Default: 'manifests/<lowercased first char of publisher>/<publisher>/<name>/<version>'.
    path: "manifests/b/beeyev/telegram-owl/{{.Version}}"
    homepage: "https://github.com/beeyev/telegram-owl"
    description: "CLI utility to send messages and media files to Telegram chats and channels — directly from your terminal"
    license_url: "https://github.com/beeyev/telegram-owl/blob/master/LICENSE"
    copyright: "Alexander Tebiev"
    copyright_url: "https://github.com/beeyev"
    skip_upload: auto
    release_notes: "{{.Changelog}}"
    release_notes_url: "https://github.com/beeyev/telegram-owl/releases/tag/v{{.Version}}"
    tags:
      - telegram
      - cli
    # Repository to push the generated files to.
    repository:
      owner: beeyev
      name: pkg

chocolateys:
  -
    name: telegram-owl
    package_source_url: https://github.com/beeyev/telegram-owl
    owners: Alexander Tebiev
    title: Telegram Owl
    authors: Alexander Tebiev
    project_url: https://github.com/beeyev/telegram-owl
    # icon_url: "https://rawcdn.githack.com/foo/bar/efbdc760-395b-43f1-bf69-ba25c374d473/icon.png"
    copyright: Alexander Tebiev
    license_url: https://github.com/beeyev/telegram-owl/blob/master/LICENSE
    require_license_acceptance: false
    project_source_url: https://github.com/beeyev/telegram-owl
    docs_url: https://github.com/beeyev/telegram-owl/blob/master/README.md
    bug_tracker_url: https://github.com/beeyev/telegram-owl/issues
    tags: "telegram"
    summary: CLI utility to send messages and files to Telegram chats and channels
    description: |
      {{ .ProjectName }} installer package.
      CLI utility to send messages and files to Telegram chats and channels
    release_notes: "https://github.com/beeyev/telegram-owl/releases/tag/v{{ .Version }}"
    # api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    source_repo: "https://push.chocolatey.org/"
